version: "3.7"
services:
  issuer-verifier-acapy:
    image: ghcr.io/findy-network/findy-agent:latest
    volumes:
      - ./conf/genesis.txt:/genesis.txt
      - ./conf/steward.exported:/steward.exported
      - ./cert:/grpc
      - .data/issuer/agent:/root
    environment:
      FCLI_POOL_GENESIS_TXN_FILE: "/genesis.txt"
      FCLI_AGENCY_GRPC_TLS: "true"
      FCLI_AGENCY_GRPC_CERT_PATH: "/grpc"
      FCLI_AGENCY_HOST_ADDRESS: issuer-verifier-nginx
      FCLI_AGENCY_HOST_PORT: 10001
      FCLI_AGENCY_SERVER_PORT: 10001
      FCLI_LOGGING: "-logtostderr -v=3"
      FCLI_AGENCY_REQUEST_TIMEOUT: "3m"
    ports:
      - "10001:10001"
      - "50051:50051"
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"

  issuer-verifier-acapy-auth:
    image: ghcr.io/findy-network/findy-agent-auth:latest
    volumes:
      - ./cert:/grpc
      - .data/issuer/auth:/data
    depends_on:
      - issuer-verifier-acapy
    environment:
      FAA_PORT: "8888"
      FAA_ORIGIN: "http://localhost:8888"
      FAA_AGENCY_ADDR: "issuer-verifier-acapy"
      FAA_TIMEOUT_SECS: "60"
    ports:
      - "8888:8888"
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"

  issuer-verifier-nginx:
    container_name: issuer-verifier-nginx
    image: nginx:latest
    volumes:
      - ./nginx-issuer-verifier-${NUMBER_OF_ISSUER_VERIFIER_ACAPY_INSTANCES}.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - issuer-verifier-acapy
    ports:
      - 10000:10000
    networks:
      - aries-load-test

  holder-acapy:
    image: ghcr.io/findy-network/findy-agent:latest
    volumes:
      - ./conf/genesis.txt:/genesis.txt
      - ./conf/steward.exported:/steward.exported
      - ./cert:/grpc
      - .data/holder/agent:/root
    environment:
      FCLI_POOL_GENESIS_TXN_FILE: "/genesis.txt"
      FCLI_AGENCY_STEWARD_DID: ""
      FCLI_AGENCY_GRPC_TLS: "true"
      FCLI_AGENCY_GRPC_CERT_PATH: "/grpc"
      FCLI_AGENCY_GRPC_PORT: 50052
      FCLI_AGENCY_HOST_ADDRESS: host.docker.internal
      FCLI_AGENCY_HOST_PORT: 10011
      FCLI_AGENCY_SERVER_PORT: 10011
      FCLI_LOGGING: "-logtostderr -v=3"
      FCLI_AGENCY_REQUEST_TIMEOUT: "3m"
    ports:
      - "10011:10011"
      - "50052:50052"
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"

  holder-acapy-auth:
    image: ghcr.io/findy-network/findy-agent-auth:latest
    volumes:
      - ./cert:/grpc
      - .data/holder/auth:/data
    depends_on:
      - holder-acapy
    environment:
      FAA_PORT: "8889"
      FAA_ORIGIN: "http://localhost:8889"
      FAA_AGENCY_ADDR: "holder-acapy"
      FAA_AGENCY_PORT: "50052"
      FAA_TIMEOUT_SECS: "60"
    ports:
      - "8889:8889"
    networks:
      - aries-load-test
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tails-server:
    container_name: tails-server
    build:
      context: ./indy-tails-server
      dockerfile: docker/Dockerfile.tails-server
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path /tmp/tails-files
        --log-level INFO

    volumes:
      - tails-server-volume:/home/indy/tails-files
    ports:
      - 6543:6543
    networks:
      - aries-load-test
    restart: always

networks:
  aries-load-test:
    external: true
    name: aries-load-test

volumes:
  tails-server-volume:
